"""Agregar columna comentario al modelo Resena

Revision ID: 409d5b1d29f7
Revises: 787ced713edc
Create Date: 2025-05-07 12:52:46.949998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '409d5b1d29f7'
down_revision = '787ced713edc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=False))
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
