"""Agregar columna correo a la tabla usuario

Revision ID: 6a4c1636fe68
Revises: 70fc52b16273
Create Date: 2025-05-07 12:29:21.485483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a4c1636fe68'
down_revision = '70fc52b16273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('correo', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('contraseña', sa.String(length=150), nullable=False))
        batch_op.drop_constraint('usuario_email_key', type_='unique')
        batch_op.create_unique_constraint(None, ['correo'])
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=150), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('usuario_email_key', ['email'])
        batch_op.drop_column('contraseña')
        batch_op.drop_column('correo')

    # ### end Alembic commands ###
