"""Recrear migraciones

Revision ID: 70fc52b16273
Revises: d4debe591825
Create Date: 2025-05-07 12:19:31.090579

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '70fc52b16273'
down_revision = 'd4debe591825'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.alter_column('director',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
        batch_op.alter_column('titulo',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)

    # ### end Alembic commands ###
