"""correccion contenido

Revision ID: 787ced713edc
Revises: dfce29cd5769
Create Date: 2025-05-07 12:43:29.490638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '787ced713edc'
down_revision = 'dfce29cd5769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
