"""Crear tablas iniciales

Revision ID: aa824d770370
Revises: 
Create Date: 2025-05-07 09:44:11.943380

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa824d770370'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pelicula',
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=200), nullable=True),
    sa.Column('director', sa.String(length=150), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_lanzamiento', sa.Date(), nullable=True),
    sa.Column('portada', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_pelicula')
    )
    op.create_table('usuario',
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('correo', sa.String(length=150), nullable=True),
    sa.Column('contraseña', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_usuario'),
    sa.UniqueConstraint('correo')
    )
    op.create_table('resena',
    sa.Column('id_resena', sa.Integer(), nullable=False),
    sa.Column('comentario', sa.Text(), nullable=True),
    sa.Column('puntuacion', sa.Integer(), nullable=True),
    sa.Column('fecha_resena', sa.DateTime(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=False),
    sa.Column('id_pelicula', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_pelicula'], ['pelicula.id_pelicula'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['usuario.id_usuario'], ),
    sa.PrimaryKeyConstraint('id_resena')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('resena')
    op.drop_table('usuario')
    op.drop_table('pelicula')
    # ### end Alembic commands ###
