"""Agregar campo portada a Pelicula

Revision ID: af9141b6d8a9
Revises: 21e6c8c3ef6e
Create Date: 2025-04-28 14:44:29.911045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'af9141b6d8a9'
down_revision = '21e6c8c3ef6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.add_column(sa.Column('portada', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pelicula', schema=None) as batch_op:
        batch_op.drop_column('portada')

    # ### end Alembic commands ###
