"""Agregar relación entre Resena y Usuario

Revision ID: bf33003cfb00
Revises: aa824d770370
Create Date: 2025-05-07 12:03:35.841720

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bf33003cfb00'
down_revision = 'aa824d770370'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.Text(), nullable=False))
        batch_op.drop_constraint('resena_id_pelicula_fkey', type_='foreignkey')
        batch_op.drop_column('comentario')
        batch_op.drop_column('puntuacion')
        batch_op.drop_column('fecha_resena')
        batch_op.drop_column('id_pelicula')

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=150), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=150), nullable=False))
        batch_op.alter_column('nombre',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=150),
               nullable=False)
        batch_op.drop_constraint('usuario_correo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['email'])
        batch_op.drop_column('correo')
        batch_op.drop_column('contraseña')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contraseña', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('correo', sa.VARCHAR(length=150), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('usuario_correo_key', ['correo'])
        batch_op.alter_column('nombre',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('password')
        batch_op.drop_column('email')

    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pelicula', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('fecha_resena', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('puntuacion', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('comentario', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('resena_id_pelicula_fkey', 'pelicula', ['id_pelicula'], ['id_pelicula'])
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###
