"""Agregar clave foránea entre Resena y Pelicula

Revision ID: d4debe591825
Revises: bf33003cfb00
Create Date: 2025-05-07 12:07:25.248973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd4debe591825'
down_revision = 'bf33003cfb00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id_pelicula', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'pelicula', ['id_pelicula'], ['id_pelicula'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('id_pelicula')

    # ### end Alembic commands ###
