"""Agregar columna comentario al modelo Resena

Revision ID: dfce29cd5769
Revises: 6a4c1636fe68
Create Date: 2025-05-07 12:38:54.732330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfce29cd5769'
down_revision = '6a4c1636fe68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comentario', sa.Text(), nullable=False))
        batch_op.drop_column('contenido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('resena', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contenido', sa.TEXT(), autoincrement=False, nullable=False))
        batch_op.drop_column('comentario')

    # ### end Alembic commands ###
